### PR TITLE
load dyamic rules locally (with working rules)

### PR DESCRIPTION
**Pull request by thatcoderguy**

### CODE REVIEW

**Comment by melithine** [comment]
It's truly ironic that this is pull request 404.

**Comment by Uyahya566** [comment]
How do we download it?

**Comment by thatcoderguy** [comment]
2 options - You can either clone the project which I forked... or use Github Desktop to pull the PR

**Comment by Uyahya566** [comment]
> 2 options - You can either clone the project which I forked... or use Github Desktop to pull the PR

Your fork is missing the OF DL.exe file and a few others but when I copied them from the original version to your code it still gives the same error

**Comment by thatcoderguy** [comment]
> > 2 options - You can either clone the project which I forked... or use Github Desktop to pull the PR
> 
> Your fork is missing the OF DL.exe file and a few others but when I copied them from the original version to your code it still gives the same error

If you pulled down the code, it have any of those missing files...  and the .exe you need to build from the codebase - that would explain why it's still not working.  If you're unfamiliar with C# it's probably worth waiting until the new release is available with my changes.

**Pull request merged**
