### PR TITLE
Add docker configuration

### PR DESCRIPTION
**Pull request by whimsical-c4lic0**
This PR contains a Dockerfile and entrypoint script to allow users to run OF-DL in a docker container. This will allow users to run OF-DL on operating systems other than Windows without having to setup a .NET development environment.

To build an OF-DL docker image, simply execute:
`docker build -t of-dl .` in the root of the repository

To run OF-DL in a docker container, then execute:
`docker run -it -v /{path to data directory}/:/data /{path to config directory}/:/config of-dl`

`{path to data directory}` should be replaced with the path to the folder on your computer where the downloaded data should be saved. `{path to config directory}` should be replaced with the path to the folder on your computer where you want to store the config for OF-DL. If `auth.json` and `config.json` don't exist in the config directory, files with default values will be created when you run the docker container.

While it is not included in this PR, you can add a simple GitHub action to automatically publish new docker images when you create new releases.

### CODE REVIEW

**Comment by sim0n00ps** [comment]
Going to test this out on my Ubuntu machine, thanks for this

**Comment by whimsical-c4lic0** [comment]
You're welcome! I've personally tested the branch natively on Ubuntu 20.04 as well as a WSL2 installation of Ubuntu 20.04 using Docker for Windows.

**Comment by whimsical-c4lic0** [comment]
Looking at the `ProcessStartInfo` object in the `DownloadDrmMedia` method, I'm not sure why the ffmpeg logs behave differently in Windows vs Linux. The default behavior for standard output redirection in dotnet processes must be different between operating systems.

No matter, my most recent commit that sets explicit values for `UseShellExecute`, `RedirectStandardOutput`, and `RedirectStandardError` seems to fix the issue.

**Comment by sim0n00ps** [comment]
Just done a scrape and ffmpeg logs no longer appear, thanks again for this

**Comment by Lebowski89** [comment]
Just adding, got this setup and working perfect via Docker Compose in UnRaid.

`  of-dl:
    image: ghcr.io/sim0n00ps/of-dl:latest
    container_name: of-dl
    network_mode: <network>
    environment:
      - TZ=<Country>/<City>
      - PUID=99
      - PGID=100
      - UMASK=022
    ports: 
      - <port>:<port>/tcp
    volumes:
      - <pathtodata>:/data:rw
      - <pathtoconfig>l:/config:rw
    restart: unless-stopped`

**Pull request merged**
