### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lerroynick**
Added a setting to rename existing files to the custom format. 
This feature has some limitations:
 1. This works only if the file is in the original file name. (i did it that way because the alternative requires another entries in the database, to keep the original filename, and the last used custom format, and this is not a production level project to accomodate all the possibilities). 
 2. Not implemented yet for DRM stuff because i haven't extracted the blobs yet so i can test these code portions. 
 
In any case this is particularly usefull if you have a lot of stuff before the custom format is introduced and its now easy to rename them without redownloading them.

### CODE REVIEW

**Comment by lerroynick** [comment]
Road map
1. Will implement the time range selection
2. Do the renaming for the DRM stuff
3. Steamline the api helper

And it should be fairly done at the moment. 
if you want any functionality that you are bored to do and you think it will be important let me know.

**Comment by sim0n00ps** [comment]
Thanks for everything you have done here and also for the stuff yesterday, most of what you did has helped massively. Do you think it would be better for you to finish the other features first before I merge?

**Comment by lerroynick** [comment]
no worries mate. Its a great project and wanted to contribute. I didn't do anything special, some cleanup only.  
About merging, is up to you. Maybe merge to keep it in sync. If you want to postpone it i should be able to get done the time range sometime today, and you can merge after that.  The Drm and the api cleanup should be done sometime this week.
My only suggestion would be to make another branch called Dev or something equivalent and merge there the future changes so that we dont intefere with the master branch immidiately.

**Comment by sim0n00ps** [comment]
I've created a Dev branch, probably should of done that a long time ago lol

**Pull request merged**
