### PR TITLE
doc: instructions on how to build and run the project in Linux

### PR DESCRIPTION
**Pull request by legendaryredfox**
Adding instructions on how to build this project on a Linux system. This has been tested in linux mint and will most likely work on any debian distros. Sorry for the wrong PR yesterday, my dumb ass cloned the wrong repo

### CODE REVIEW

**Comment by scabaa** [comment]
I assume it's a typo but when you cloning the OF-DL repo then it will create the same directory name. But you mentioned 'OF DL' several times after that as dir name (without the dash).

**Comment by legendaryredfox** [comment]
I double-checked the file structure and I believe there is no typo, as per the image 
image

**Comment by scabaa** [comment]
Actually the issue is only with the first cd after cloning the repo. Line 17

**Comment by legendaryredfox** [comment]
You were right, just corrected it

**Pull request merged**
