### PR TITLE
The setting to assign the timeout value on the new config got lost on…

### PR DESCRIPTION
**Pull request by lerroynick**
The setting to assign the timeout value on the new config got lost on the refactor merge because i was 1 commit behind. This restores it.

### CODE REVIEW

**Comment by sim0n00ps** [comment]
I'm almost finished with what I'm working on so I will add this in my commit instead

**Comment by lerroynick** [comment]
Cool. i have also made some changes to
1. Rename existing files when the custom format is selected. 
2. Add the ability to download all posts or posts between 2 datetime ranges. 
I will wait for your commits first to avoid any conflicts this time.

**Comment by sim0n00ps** [comment]
Sounds good, you're probably going to have to re-jig what you've done after I've finished as I am modifying the DownloadHelper

**Comment by lerroynick** [comment]
not a problem.

**Comment by sim0n00ps** [comment]
I've just pushed

**Pull request closed without merging**
